"""timekeeping mvp

Revision ID: f1047f0760af
Revises: 0001_init
Create Date: 2026-01-20 22:22:33.251451

"""
from alembic import op
import sqlalchemy as sa

revision = 'f1047f0760af'
down_revision = '0001_init'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tk_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=32), nullable=False),
    sa.Column('make_model', sa.String(length=128), nullable=True),
    sa.Column('navisoft_device_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tk_vehicles_id'), 'tk_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_tk_vehicles_plate'), 'tk_vehicles', ['plate'], unique=True)
    op.create_table('tk_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tk_employees_id'), 'tk_employees', ['id'], unique=False)
    op.create_index(op.f('ix_tk_employees_user_id'), 'tk_employees', ['user_id'], unique=True)
    op.create_table('tk_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('urlop', 'l4', 'inne', name='tk_absence_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['tk_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tk_absences_date_from'), 'tk_absences', ['date_from'], unique=False)
    op.create_index(op.f('ix_tk_absences_date_to'), 'tk_absences', ['date_to'], unique=False)
    op.create_index(op.f('ix_tk_absences_employee_id'), 'tk_absences', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tk_absences_id'), 'tk_absences', ['id'], unique=False)
    op.create_table('tk_crew_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'locked', name='tk_crew_log_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['tk_employees.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['tk_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_date', 'vehicle_id', name='uq_tk_crew_logs_work_date_vehicle')
    )
    op.create_index(op.f('ix_tk_crew_logs_created_by_employee_id'), 'tk_crew_logs', ['created_by_employee_id'], unique=False)
    op.create_index(op.f('ix_tk_crew_logs_id'), 'tk_crew_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tk_crew_logs_vehicle_id'), 'tk_crew_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_tk_crew_logs_work_date'), 'tk_crew_logs', ['work_date'], unique=False)
    op.create_table('tk_daily_status_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('praca', 'urlop', 'l4', 'inne', 'nieobecny_do_klasyfikacji', name='tk_daily_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['tk_employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_tk_daily_status_overrides_employee_date')
    )
    op.create_index(op.f('ix_tk_daily_status_overrides_employee_id'), 'tk_daily_status_overrides', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tk_daily_status_overrides_id'), 'tk_daily_status_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_tk_daily_status_overrides_work_date'), 'tk_daily_status_overrides', ['work_date'], unique=False)
    op.create_table('tk_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('is_ad_hoc', sa.Boolean(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['tk_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tk_sites_id'), 'tk_sites', ['id'], unique=False)
    op.create_index(op.f('ix_tk_sites_name'), 'tk_sites', ['name'], unique=False)
    op.create_table('tk_crew_log_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_log_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('override_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crew_log_id'], ['tk_crew_logs.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['tk_employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_log_id', 'employee_id', name='uq_tk_crew_log_members_log_employee')
    )
    op.create_index(op.f('ix_tk_crew_log_members_crew_log_id'), 'tk_crew_log_members', ['crew_log_id'], unique=False)
    op.create_index(op.f('ix_tk_crew_log_members_employee_id'), 'tk_crew_log_members', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tk_crew_log_members_id'), 'tk_crew_log_members', ['id'], unique=False)
    op.create_table('tk_crew_work_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_log_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crew_log_id'], ['tk_crew_logs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['tk_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tk_crew_work_segments_crew_log_id'), 'tk_crew_work_segments', ['crew_log_id'], unique=False)
    op.create_index(op.f('ix_tk_crew_work_segments_end_at'), 'tk_crew_work_segments', ['end_at'], unique=False)
    op.create_index(op.f('ix_tk_crew_work_segments_id'), 'tk_crew_work_segments', ['id'], unique=False)
    op.create_index(op.f('ix_tk_crew_work_segments_site_id'), 'tk_crew_work_segments', ['site_id'], unique=False)
    op.create_index(op.f('ix_tk_crew_work_segments_start_at'), 'tk_crew_work_segments', ['start_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tk_crew_work_segments_start_at'), table_name='tk_crew_work_segments')
    op.drop_index(op.f('ix_tk_crew_work_segments_site_id'), table_name='tk_crew_work_segments')
    op.drop_index(op.f('ix_tk_crew_work_segments_id'), table_name='tk_crew_work_segments')
    op.drop_index(op.f('ix_tk_crew_work_segments_end_at'), table_name='tk_crew_work_segments')
    op.drop_index(op.f('ix_tk_crew_work_segments_crew_log_id'), table_name='tk_crew_work_segments')
    op.drop_table('tk_crew_work_segments')
    op.drop_index(op.f('ix_tk_crew_log_members_id'), table_name='tk_crew_log_members')
    op.drop_index(op.f('ix_tk_crew_log_members_employee_id'), table_name='tk_crew_log_members')
    op.drop_index(op.f('ix_tk_crew_log_members_crew_log_id'), table_name='tk_crew_log_members')
    op.drop_table('tk_crew_log_members')
    op.drop_index(op.f('ix_tk_sites_name'), table_name='tk_sites')
    op.drop_index(op.f('ix_tk_sites_id'), table_name='tk_sites')
    op.drop_table('tk_sites')
    op.drop_index(op.f('ix_tk_daily_status_overrides_work_date'), table_name='tk_daily_status_overrides')
    op.drop_index(op.f('ix_tk_daily_status_overrides_id'), table_name='tk_daily_status_overrides')
    op.drop_index(op.f('ix_tk_daily_status_overrides_employee_id'), table_name='tk_daily_status_overrides')
    op.drop_table('tk_daily_status_overrides')
    op.drop_index(op.f('ix_tk_crew_logs_work_date'), table_name='tk_crew_logs')
    op.drop_index(op.f('ix_tk_crew_logs_vehicle_id'), table_name='tk_crew_logs')
    op.drop_index(op.f('ix_tk_crew_logs_id'), table_name='tk_crew_logs')
    op.drop_index(op.f('ix_tk_crew_logs_created_by_employee_id'), table_name='tk_crew_logs')
    op.drop_table('tk_crew_logs')
    op.drop_index(op.f('ix_tk_absences_id'), table_name='tk_absences')
    op.drop_index(op.f('ix_tk_absences_employee_id'), table_name='tk_absences')
    op.drop_index(op.f('ix_tk_absences_date_to'), table_name='tk_absences')
    op.drop_index(op.f('ix_tk_absences_date_from'), table_name='tk_absences')
    op.drop_table('tk_absences')
    op.drop_index(op.f('ix_tk_employees_user_id'), table_name='tk_employees')
    op.drop_index(op.f('ix_tk_employees_id'), table_name='tk_employees')
    op.drop_table('tk_employees')
    op.drop_index(op.f('ix_tk_vehicles_plate'), table_name='tk_vehicles')
    op.drop_index(op.f('ix_tk_vehicles_id'), table_name='tk_vehicles')
    op.drop_table('tk_vehicles')
    # ### end Alembic commands ###
