"""add segment_type to tk_crew_work_segments

Revision ID: fe9be68fb91e
Revises: f1047f0760af
Create Date: 2026-01-22 06:38:49.793076

"""
from alembic import op
import sqlalchemy as sa

revision = 'fe9be68fb91e'
down_revision = 'f1047f0760af'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tk_crew_work_segments', sa.Column('segment_type', sa.Enum('work', 'travel', name='tk_segment_type'), nullable=False, server_default='work'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tk_crew_work_segments', 'segment_type')
    # ### end Alembic commands ###

